<a href="https://colab.research.google.com/github/shanmughapriyaa12/FDS2/blob/main/FDS6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Read the dataset
df = pd.read_excel('/content/pre-process_datasample.csv')

print(df)
print("")

# Fill missing value in Country with mode
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

# Separate features and label
features = df.iloc[:, :-1].values
label = df.iloc[:, -1].values

# Handle missing values in Age and Salary
from sklearn.impute import SimpleImputer

age = SimpleImputer(strategy="mean", missing_values=np.nan)
salary = SimpleImputer(strategy="mean", missing_values=np.nan)

age.fit(features[:, [1]])
salary.fit(features[:, [2]])

features[:, [1]] = age.transform(features[:, [1]])
features[:, [2]] = salary.transform(features[:, [2]])

print("After handling missing values:")
print(features)
print("")

# One Hot Encoding for Country
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)

Country = oh.fit_transform(features[:, [0]])

print("One Hot Encoded Country:")
print(Country)
print("")

# Combine encoded Country with Age and Salary
final_set = np.concatenate(
    (Country, features[:, [1, 2]]),
    axis=1
)

print("Final Dataset:")
print(final_set)
print("")


from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(final_set)

feat_standard_scaler = sc.transform(final_set)

print("Standard Scaled Data:")
print(feat_standard_scaler)
print("")


from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler(feature_range=(0, 1))

mms.fit(final_set)

feat_minmax_scaler = mms.transform(final_set)

print("Min-Max Scaled Data:")
print(feat_minmax_scaler)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

After handling missing values:
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

One Hot Encoded Country:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

Final Dataset:
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 6377